# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(to='app01.Students'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
