# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181130_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Students')),
            ],
        ),
    ]
